### ISSUE TITLE
Adecuacion Script Instalacion de Objetos

### ISSUE THREAD

**Issue by Jodainc** [DaJoInc/Pacrim-Lords#11]
Buen día se solicita una adecuacion al script de Objetos

**Comment by Jodainc** [comment]
https://github.com/DaJoInc/Pacrim-Lords/pull/12/commits/5621335772b67c4725f8164ea29883ed7a5c888d

Solicita cierra con commit

**Comment by TheOverLordKotan** [comment]
No se subio el nuevo modelo y su eap

**Comment by Jodainc** [comment]
Buen dia se sube con  el commit 
https://github.com/DaJoInc/Pacrim-Lords/commit/bb86547d8db1bb97c08d579e876c1af8d374bee8
